Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true

  config.vm.provision :salt do |salt|
    salt.run_highstate = true
    salt.minion_config = "minion.conf"
  end
end

Vagrant.configure("1") do |config|
  ## Chose your base box
  config.vm.box = "centos6"

  ## For masterless, mount your salt file root
  config.vm.share_folder "salt_file_root", "/srv", "../"
end
