Vagrant.configure("2") do |config|
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"
  config.vm.box = "centos65"
  config.vm.synced_folder "../", "/srv/"
  config.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
  config.vm.provision :salt do |salt|
    salt.run_highstate = true
    salt.minion_config = "minion.conf"
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
end
