Vagrant::Config.run do |config|
  ## Chose your base box
  config.vm.box = "centos6"

  ## For masterless, mount your salt file root
  config.vm.share_folder "salt_file_root", "/srv", "../"

  config.vm.forward_port 80, 8000

  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.run_highstate = true

    ## Optional Settings:
    salt.minion_config = "minion.conf"
    # salt.temp_config_dir = "/existing/folder/on/basebox/"
    salt.salt_install_type = "git"
    salt.salt_install_args = "postgres_db_fix"

    ## If you have a remote master setup, you can add
    ## your preseeded minion key
    # salt.minion_key = "salt/key/minion.pem"
    # salt.minion_pub = "salt/key/minion.pub"
  end
end
