Vagrant::Config.run do |config|
  ## Chose your base box
  config.vm.box = "debian6"

  ## For masterless, mount your salt file root
  config.vm.share_folder "salt_file_root", "/srv", "../"

  config.vm.forward_port 80, 8000

  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.run_highstate = true

    ## Optional Settings:
    salt.minion_config = "minion.conf"
  end
end
