Vagrant.configure("2") do |config|
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "saucy64"
  config.vm.synced_folder "../", "/srv/"
  config.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
  config.vm.provision :salt do |salt|
    salt.run_highstate = true
    salt.minion_config = "minion.conf"
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
end
