Vagrant.configure("2") do |config|
#  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"
#  config.vm.box = "raring64"
  config.vm.box = "precise64"
  config.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
  config.vm.provision :salt do |salt|
    salt.run_highstate = true
    salt.minion_config = "minion.conf"
  end
end

Vagrant.configure("1") do |config|
  config.vm.share_folder "salt_file_root", "/srv", "../"
end
